read_sdc $::env(SCRIPTS_DIR)/base.sdc

#create_generated_clock -name p00_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p00_I.clk}]
create_generated_clock -name p01_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p01_I.clk}]
create_generated_clock -name p02_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p02_I.clk}]
create_generated_clock -name p03_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p03_I.clk}]
create_generated_clock -name p04_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p04_I.clk}]
create_generated_clock -name p05_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p05_I.clk}]
create_generated_clock -name p06_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p06_I.clk}]
create_generated_clock -name p07_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p07_I.clk}]
#create_generated_clock -name p08_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p08_I.clk}]
create_generated_clock -name p09_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p09_I.clk}]
create_generated_clock -name p10_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p10_I.clk}]
create_generated_clock -name p11_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p11_I.clk}]
create_generated_clock -name p12_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p12_I.clk}]
create_generated_clock -name p13_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p13_I.clk}]
create_generated_clock -name p14_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p14_I.clk}]
create_generated_clock -name p15_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p15_I.clk}]
create_generated_clock -name p16_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p16_I.clk}]
create_generated_clock -name p17_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p17_I.clk}]
create_generated_clock -name p18_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p18_I.clk}]
create_generated_clock -name p19_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p19_I.clk}]
create_generated_clock -name p20_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p20_I.clk}]
create_generated_clock -name p21_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p21_I.clk}]
create_generated_clock -name p22_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p22_I.clk}]
create_generated_clock -name p23_clk -source [get_ports {tt_clk_Y}] -combinational -divide_by 1 [get_nets {mux_inst.p23_I.clk}]
